### ISSUE TITLE
[publish] dpmpy publish

### ISSUE THREAD

**Issue by kittdotech** [frictionlessdata/dpmpy#19] opened 2016-10-27 13:52 UTC
While Publishing Datapackage, Got the following error.

> Original error was: ValueError('No JSON object could be decoded',)
> Invalid JSON response from server

**Comment by Fak3** [comment] 2016-10-27 14:05
Duplicate of https://github.com/frictionlessdata/dpr-api/issues/2 url endpoint on the server should be changed to /api/package/{publisher}/{dpname}

**Closed by Fak3** 2016-10-27 14:05 UTC
